### ISSUE TITLE
Does this work in JSPs?

### ISSUE THREAD

**Issue by dan-silk-discovery** [tushortz/JavaIME#1]
It doesn't seem to recognize JSP syntax for imports. For example, I have this at the top of my page: 

`<%@ page import="com.projectname.common.services.response.SccResponse" %>`

But there are no suggestions for one of my objects defined in the SccResponse library.

**Comment by tushortz** [comment]
It doesn't support `JSP`. Only `JavaSE` and `JavaFX` @ScrippsFEE
