### ISSUE TITLE
Typo causes malfunction

### ISSUE THREAD

**Issue by RobbinDG** [tushortz/JavaIME#4]
I downloaded this, and found that it only showed me the I-xxxx autocompletions. After some tinkering, I found that in a file with shortcut specifications (there are multiple, I cant remember which exactly), there is a [ indented too far, making the whole file incorrect because of strict syntax rules in (probably) JSON. Just moving the bracket, fixed the issue.

**Comment by tushortz** [comment]
@RobbinDG thanks for notifying me. please can you create a pull request with the fixes you made on your local copy
